"""init: movies

Revision ID: 92ca083140d8
Revises: 
Create Date: 2024-04-15 23:19:28.046623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92ca083140d8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('imdb', sa.String(), nullable=False),
    sa.Column('poster', sa.String(), nullable=False),
    sa.Column('plot', sa.String(), nullable=False),
    sa.Column('year', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("year ~ '^(1[89]\\d{2}|20\\d{2})$'", name='check_movies_year_regex'),
    sa.CheckConstraint('"imdb" ~ \'^tt\\d{7,}$\'', name='check_movies_imdb_regex'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imdb', name='unique_movies_imdb'),
    sa.UniqueConstraint('title', name='unique_movies_title')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movies')
    # ### end Alembic commands ###
