"""init: movies

Revision ID: 9dcac04a52fd
Revises: 
Create Date: 2024-04-03 10:24:51.890594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dcac04a52fd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('imdb', sa.String(), nullable=False),
    sa.Column('poster', sa.String(), nullable=False),
    sa.Column('plot', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("imdb ~ '^tt\\d{7}$'", name='check_movies_imdb_regex'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imdb', name='unique_movies_imdb'),
    sa.UniqueConstraint('title', name='unique_movies_title')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movies')
    # ### end Alembic commands ###
