"""init: movies

Revision ID: acead4f8dce4
Revises: 
Create Date: 2024-04-04 13:36:30.912681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acead4f8dce4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('imdbID', sa.String(), nullable=False),
    sa.Column('poster', sa.String(), nullable=False),
    sa.Column('plot', sa.String(), nullable=False),
    sa.Column('year', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("year ~ '^(1[89]\\d{2}|20\\d{2})$'", name='check_movies_year_regex'),
    sa.CheckConstraint('"imdbID" ~ \'^tt\\d{7,}$\'', name='check_movies_imdbID_regex'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imdbID', name='unique_movies_imdbID'),
    sa.UniqueConstraint('title', name='unique_movies_title')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movies')
    # ### end Alembic commands ###
