"""init: movies

Revision ID: ee932383ea4d
Revises: 
Create Date: 2024-04-02 22:27:18.090808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee932383ea4d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('imdb', sa.String(), nullable=False),
    sa.Column('poster', sa.String(), nullable=False),
    sa.Column('plot', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("imdb ~ '^tt\\d{7}$'", name='check_movies_imdb_regex'),
    sa.CheckConstraint("poster = 'N/A' OR poster ~ '^https?:\\/\\/(?NULL\\.)?[-a-zA-Z0-9@:%%._\\+~#=]{1,256}\\.[a-zA-Z0-9()]{1,6}\\b(?:[-a-zA-Z0-9()@:%%_\\+.~#?&\\/=]*)$'", name='check_movies_imdb_poster'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imdb', name='unique_movies_imdb'),
    sa.UniqueConstraint('title', name='unique_movies_title')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movies')
    # ### end Alembic commands ###
