name: Проверка
on: [push]
jobs:
  linter:
    name: Линтер
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.2
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install flake8==7.0.0 wemake-python-styleguide==0.19.2
    - name: Flake8
      run: flake8

  tests:
    name: Тесты
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.2
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --without=dev --without=docker
        pip install pytest==8.1.1
    - name: Pytest
      run: pytest
